mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090
proxy-providers:
  #å…¨éƒ¨èŠ‚ç‚¹

  TEMPORARY: 
    type: http
    url: "https://api.v1.mk/sub?target=clash&url=https://gist.githubusercontent.com/yaney01/015dc32841583581e391e5358a520490/raw/qd|http://shoujiyanxishe.tk/link/BIJCvNVlh7iP6kYT?sub=3#udp=1&emoji=2&emoji=true&list=true&udp=true"
    interval: 600
    path: ./proxy/TEMPORARY.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204  

dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:10053
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29 
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.xboxlive.com'
    - 'msftconnecttest.com'
    - 'xbox.*.microsoft.com'
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net'
  nameserver:
    - https://dns.alidns.com/dns-query

proxies:

proxy-groups:
  - name: ğŸš€ MAN
    type: select
    use: 
      - TEMPORARY
    proxies:
      - âœˆï¸ AUT
    url: "http://www.gstatic.com/generate_204"
    interval: 86400
  - name: âœˆï¸ AUT
    type: url-test
    use: 
      - TEMPORARY
    url: "http://www.gstatic.com/generate_204"
    interval: 86400

  - name: ğŸŒ Global
    type: select
    proxies: 
      - ğŸš€ MAN
      - âœˆï¸ AUT

  - name: ğŸ Global Media
    type: select
    proxies:
      - ğŸš€ MAN
      - âœˆï¸ AUT

  - name: ğŸ‡¨ğŸ‡³ Mainland
    type: select
    proxies: 
      - DIRECT
      - ğŸš€ MAN
      - âœˆï¸ AUT

  - name: ğŸ“º BiliBili
    type: select
    proxies: 
      - DIRECT
      - ğŸš€ MAN
      - âœˆï¸ AUT

  - name: ğŸŸ Fish
    type: select
    proxies: 
      - ğŸš€ MAN
      - âœˆï¸ AUT

  - name: ğŸš« Block Ads
    type: select
    proxies: 
      - REJECT

  
rule-providers:

  BiliBili:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml"
    path: ./ruleset/BiliBili.yaml
    interval: 86400

  China:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Classical.yaml"
    path: ./ruleset/China.yaml
    interval: 86400

  Global:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global_Classical.yaml"
    path: ./ruleset/Global-Domain.yaml
    interval: 86400

  GlobalMedia:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Classical.yaml"
    path: ./ruleset/GlobalMedia_Classical.yaml
    interval: 86400

  Lan:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml"
    path: ./ruleset/lan.yaml
    interval: 86400
  
  Privacy:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Privacy/Privacy_Classical.yaml"
    path: ./ruleset/Privacy.yaml
    interval: 86400

  Hijacking:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Hijacking/Hijacking.yaml"
    path: ./ruleset/Hijacking.yaml
    interval: 86400
  
rules:
  - RULE-SET,BiliBili,ğŸ“º BiliBili
  - RULE-SET,GlobalMedia,ğŸ Global Media
  - RULE-SET,Global,ğŸŒ Global
  - RULE-SET,China,ğŸ‡¨ğŸ‡³ Mainland
  - RULE-SET,Lan,ğŸ‡¨ğŸ‡³ Mainland
  - GEOIP,CN,ğŸ‡¨ğŸ‡³ Mainland
  - RULE-SET,Privacy,ğŸš« Block Ads
  - RULE-SET,Hijacking,ğŸš« Block Ads
  - MATCH,ğŸŸ Fish
