mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
subscribe-url: è®¢é˜…é“¾æŽ¥
proxy-providers:
  All: &All
    type: http
    url: "https://api.v1.mk/sub?target=clash&url=è®¢é˜…é“¾æŽ¥&list=true&udp=true&emoji=true"
    interval: 86400
    path: ./all.yaml
    health-check:
      enable: true
      interval: 36000
      url: http://www.gstatic.com/generate_204
  Music:
    type: http
    url: "https://api.v1.mk/sub?target=clash&url=https://raw.githubusercontent.com/nameking77/Qx/main/music/wyy.txt&list=true&udp=true"
    interval: 86400
    path: ./proxy/NetEaseMusic.yaml
    health-check:
      enable: true
      interval: 36000
      url: http://apm3.music.163.com
  US:
    <<: *All 
    filter: ç¾Ž|ðŸ‡ºðŸ‡²|US|(?i)States|American

  HK:
    <<: *All
    filter: æ¸¯|ðŸ‡­ðŸ‡°|HK|(?i)Hong

  JP:
    <<: *All
    filter: æ—¥|ðŸ‡¯ðŸ‡µ|ä¸œäº¬|JP|(?i)Japan|ToKyo|å¤§é˜ª

  TW:
    <<: *All
    filter: å°|ðŸ‡¨ðŸ‡³|ðŸ‡¹ðŸ‡¼|æ¹¾|TW|(?i)Taiwan

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  default-nameserver:
  - 119.29.29.29
  - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - localhost.ptlogin2.qq.com
  - '+.srv.nintendo.net'
  - '+.stun.playstation.net'
  - '+.msftconnecttest.com'
  - '+.msftncsi.com'
  - '+.xboxlive.com'
  - 'msftconnecttest.com'
  - 'xbox.*.microsoft.com'
  - '*.battlenet.com.cn'
  - '*.battlenet.com'
  - '*.blzstatic.cn'
  - '*.battle.net'
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  - quic://c.passcloud.xyz:784
  fallback:
  - https://8.8.4.4/dns-query
  - https://1.0.0.1/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
proxies:
- name: 'ç½‘æ˜“äº‘TG'
  type: http
  server: 119.176.253.89
  port: 9080
  
proxy-groups:
  - name: æ‰‹åŠ¨åˆ‡æ¢
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Rocket.png
    use:
      - All
    proxies:
      - è‡ªåŠ¨é€‰æ‹©
      - æ•…éšœè½¬ç§»

  - name: è‡ªåŠ¨é€‰æ‹©
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Auto.png
    use: 
       - All
    url: "http://www.gstatic.com/generate_204"
    interval: 84600
    
  - name: æ•…éšœè½¬ç§»
    type: fallback
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Bypass.png
    url: 'http://www.gstatic.com/generate_204'
    interval: 84600
    use: 
       - All
       
  - name: å›½å¤–ç½‘ç«™
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.png
    proxies: &G
      - æ‰‹åŠ¨åˆ‡æ¢
      - è‡ªåŠ¨é€‰æ‹©
      - æ•…éšœè½¬ç§»
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾Žå›½èŠ‚ç‚¹

  - name: å›½å†…ç½‘ç«™
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/China_Map.png
    proxies: &C
      - DIRECT
      - æ‰‹åŠ¨åˆ‡æ¢
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹

      
  - name: æ²¹ç®¡
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png
    proxies:
      *G

  - name: ç”µæŠ¥
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Telegram.png
    proxies:
      *G

  - name: æŽ¨ç‰¹
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Twitter.png
    proxies:
      *G

  - name: è„¸ä¹¦
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Facebook.png
    proxies:
      *G

  - name: Ins
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Instagram.png
    proxies:
      *G
      
  - name: TikTok
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/TikTok.png
    proxies:
      *G

  - name: å“”å“©å“”å“©
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/bilibili_3.png
    proxies:
      *C

  - name: ç½‘æ˜“äº‘éŸ³ä¹
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Netease_Music.png
    use: 
      - Music
    proxies:
      - DIRECT
      - ç½‘æ˜“äº‘TG      

  - name: è‹¹æžœæœåŠ¡
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Apple.png
    proxies:
      *C

  - name: å¾®è½¯æœåŠ¡
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Microsoft.png
    proxies:
      *G
  - name: è°·æ­ŒæœåŠ¡
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Google_Search.png
    proxies:
      *G

  - name: AdBlock
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Advertising.png
    proxies:
      - REJECT
      
  - name: æ¼ç½‘ä¹‹é±¼
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Final.png
    proxies:
      *G

  - name: é¦™æ¸¯èŠ‚ç‚¹
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Hong_Kong.png
    use:
      - HK
    interval: 84600
      
  - name: å°æ¹¾èŠ‚ç‚¹
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Taiwan.png
    use:
      - TW
    interval: 84600
            
  - name: æ—¥æœ¬èŠ‚ç‚¹
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Japan.png
    use:
      - JP
    interval: 84600
      
  - name: ç¾Žå›½èŠ‚ç‚¹
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/United_States.png
    use:
      - US
    interval: 84600

rule-providers:

  Unbreak:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Unbreak.yaml"
    path: ./ruleset/Unbreak.yaml
    interval: 86400
    
  AD-Ban:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Coldvvater/Clash/master/RuleSet/AD-Ban.yaml"
    path: ./ruleset/AD-Ban.yaml
    interval: 86400

  Privacy:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Coldvvater/Clash/master/RuleSet/Privacy.yaml"
    path: ./ruleset/Privacy.yaml
    interval: 86400

  Hijacking:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Guard/Hijacking.yaml"
    path: ./ruleset/Hijacking.yaml
    interval: 86400

  YouTube:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml"
    path: ./ruleset/YouTube.yaml
    interval: 86400

  BiliBili:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml"
    path: ./ruleset/BiliBili.yaml
    interval: 86400

  Facebook:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Facebook/Facebook.yaml"
    path: ./ruleset/Facebook.yaml
    interval: 86400

  Instagram:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Instagram/Instagram.yaml"
    path: ./ruleset/Instagram.yaml
    interval: 86400

  Telegram:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml"
    path: ./ruleset/Telegram.yaml
    interval: 86400
    
  TikTok:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.yaml"
    path: ./ruleset/TikTok.yaml
    interval: 86400
    
  Twitter:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.yaml"
    path: ./ruleset/Twitter.yaml
    interval: 86400
    
  Apple:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml"
    path: ./ruleset/Apple.yaml
    interval: 86400

  Microsoft:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml"
    path: ./ruleset/Microsoft.yaml
    interval: 86400

  Google:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml"
    path: ./ruleset/Google.yaml
    interval: 86400

  NetEaseMusic:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/NetEaseMusic/NetEaseMusic.yaml"
    path: ./ruleset/NetEaseMusic.yaml
    interval: 86400


  China:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml"
    path: ./ruleset/China.yaml
    interval: 86400

  Global:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Global.yaml"
    path: ./ruleset/Global.yaml
    interval: 86400

  Lan:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml"
    path: ./ruleset/lan.yaml
    interval: 86400
    
rules:
  - RULE-SET,Unbreak,DIRECT
  - RULE-SET,AD-Ban,AdBlock
  - RULE-SET,Privacy,AdBlock
  - RULE-SET,Hijacking,AdBlock
  - RULE-SET,YouTube,æ²¹ç®¡
  - RULE-SET,TikTok,TikTok
  - RULE-SET,Facebook,è„¸ä¹¦
  - RULE-SET,Instagram,Ins
  - RULE-SET,Telegram,ç”µæŠ¥
  - RULE-SET,Twitter,æŽ¨ç‰¹
  - RULE-SET,BiliBili,å“”å“©å“”å“©
  - RULE-SET,NetEaseMusic,ç½‘æ˜“äº‘éŸ³ä¹
  - RULE-SET,Apple,è‹¹æžœæœåŠ¡
  - RULE-SET,Microsoft,å¾®è½¯æœåŠ¡
  - RULE-SET,Google,è°·æ­ŒæœåŠ¡
  - RULE-SET,Global,å›½å¤–ç½‘ç«™
  - RULE-SET,China,å›½å†…ç½‘ç«™
  - RULE-SET,Lan,DIRECT
  - GEOIP,CN,å›½å†…ç½‘ç«™
  - MATCH,æ¼ç½‘ä¹‹é±¼
